### ISSUE TITLE
About invalid utf-8

### ISSUE THREAD

**Issue by jawira** [nicjansma/mysql-convert-latin1-to-utf8#15]
Hello, I was just passing by and I saw your problem **Invalid UTF-8 data** in your README file.

After having seen your source code, I think the bug comes to the fact that your are using `utf8` instead of `utf8mb4`.  The problem is that MYSQL's `utf8` uses only 3 bytes, while it should be using 4 bytes.

In practice this means you should be using `utf8mb4_unicode_ci` and not `utf8_unicode_ci`.

Source: https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434

I hope this helps you.

**Comment by nicjansma** [comment]
Great research @jawira! I've updated the README with a link to that article too.
