### ISSUE TITLE
A comment about 'Invalid UTF-8 data'

### ISSUE THREAD

**Issue by jhundley9109** [nicjansma/mysql-convert-latin1-to-utf8#9]
My guess as to why you were running into invalid UTF-8 data when doing your conversion has to do with MySQL only storing 3 bytes of unicode in the native UTF8 character set. If you were to use utf8mb4 instead of UTF8, you may not have ran into this issue. 

This is just a note for the author and/or any body who, like me, is struggling with UTF-8 data stored in a latin1 column.

**Comment by nicjansma** [comment]
Thanks @jhundley9109!
